---
name: Close Pull Request

on:
  pull_request:

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: thollander-actions-comment-pull-request@v1
        with:
          message: |
            Hi @${{ github.actor }}!
            Please take your time and re-read the **Contributing** section in
            the README.md file, specifically:

              > I do not accept any pull requests whatsoever.

            Thanks.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close PR
        run: gh pr close ${{ github.event.pull_request.number }}
